# Generated by Django 3.2.2 on 2021-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='interest',
            field=models.FloatField(default='0'),
        ),
    ]
