# Generated by Django 3.2.2 on 2021-05-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_deposit_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='interest',
        ),
    ]
